apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istio-base
  namespace: istio-system
spec:
  interval: 10m
  releaseName: base
  install:
    createNamespace: true
  chart:
    spec:
      chart: base
      version: 1.17.2
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: iomete-system

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istiod
  namespace: istio-system
spec:
  dependsOn:
    - name: istio-base
  interval: 10m
  releaseName: istiod
  install:
    createNamespace: true
  chart:
    spec:
      chart: istiod
      version: 1.17.2
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: iomete-system
  values:
    global:
      defaultPodDisruptionBudget:
        enabled: false
    meshConfig:
      accessLogFile: "/dev/stdout"

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istio-ingress
  namespace: istio-system
spec:
  dependsOn:
    - name: istio-base
    - name: istiod
  interval: 10m
  releaseName: istio-ingress
  install:
    createNamespace: true
  chart:
    spec:
      chart: gateway
      version: 1.17.2
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: iomete-system
  values:
    service:
      annotations:
        "service.beta.kubernetes.io/aws-load-balancer-type": "elb"
        "service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout": "600"
