apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: karpenter
  namespace: karpenter
spec:
  interval: 5m
  releaseName: karpenter
  chart:
     spec:
      chart: karpenter
      version: "v0.19.3"
      sourceRef:
        kind: HelmRepository
        name: iomete
        namespace: iomete-system
  values:
    serviceAccount:
      annotations:
        "eks.amazonaws.com/role-arn": {{ .Values.karpenter.irsaArn | quote }}
    settings:
      aws:
        clusterName: {{ .Values.eks.name | quote }}
        clusterEndpoint: {{ .Values.eks.endpoint | quote }}
        defaultInstanceProfile: {{ .Values.karpenter.defaultInstanceProfile | quote }}
        interruptionQueueName: {{ .Values.karpenter.interruptionQueueName | quote }}
        vmMemoryOverheadPercent: 0.015
    replicas: 1
 