apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metric-server
  namespace: kube-system
spec:
  interval: 5m
  releaseName: k8s-metric-server
  chart:
     spec:
      chart: k8s-metric-server
      version: 1.0.3
      sourceRef:
        kind: HelmRepository
        name: iomete
        namespace: iomete-system
  values:
    replicas: 1 # default is 2