apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: spark-operator
spec:
  interval: 5m
  releaseName: spark-operator
  chart:
     spec:
      chart: spark-operator
      version: 1.1.5
      sourceRef:
        kind: HelmRepository
        name: iomete
        namespace: iomete-system
  values:
    serviceAccounts:
      sparkoperator:
        create: true
        name: {{ .Values.sparkOperatorServiceAccountName }}
        annotations:
          eks.amazonaws.com/role-arn: {{ .Values.clusterRoleArn }}